                                                            
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      MONGO_URL: mongodb://db:27017/mydatabase
    depends_on:
      - db

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


