version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
