name: Node.js CI

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull request targeting 'master' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The operating system to run the job on

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # List files in the repository to verify the directory structure
    - name: List files in the repository
      run: ls -R  # Recursively list all files in the repository to verify structure

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node.js version

    # Install dependencies
    - name: Install dependencies
      working-directory: ./Task2  # Change to the correct directory here
      run: npm install

    # Ensure executable permissions for Jest
    - name: Set executable permissions for Jest
      run: chmod +x ./Task2/node_modules/.bin/jest  # Ensure Jest is executable

    # Run tests
    - name: Run tests
      working-directory: ./Task2  # Change to the correct directory here
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "
          cd /path/to/your/app &&
          git pull origin master &&
          npm install &&
          pm2 restart app || npm start
        "
