name: Node.js CI

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull request targeting 'master' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The operating system to run the job on

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js   # Set up the Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node.js version

    # Install dependencies
    - name: Install dependencies # Install project dependencies
      working-directory: ./crocobet_task/Task2  # Set the correct directory here
      run: npm install

    # Run tests
    - name: Run tests # Run the tests with Jest
      working-directory: ./crocobet_task/Task2  # Set the correct directory here
      run: npm test
